### ISSUE TITLE
v0.9.5-alpha issues on 10.9

### ISSUE THREAD

**Issue by randi120** [mpflanzer/splitshow#28]
hi, 
I am having some issues with v0.9.5-alpha release. I am on 10.9.4. 
I can't run the compiled app (it doesn't start up properly). 
I cloned the repo, and tried to compile from source. There I ran into some issues as well. 
/splitshow/SplitShow/PreviewController.m:21:12: No visible @interface for 'NSViewController' declares the selector 'viewDidLoad'
commented the line out (after a quick search http://stackoverflow.com/questions/26345607/viewdidload-not-declared-in-nsviewcontroller) 

then ran into 
/splitshow/SplitShow/AppDelegate.m:37:41: Use of undeclared identifier 'NSStoryboard'
this is a new feature of 10.10, not available earlier (according to https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSStoryboard_Class/index.html#//apple_ref/occ/cl/NSStoryboard)
I have no idea how to tackle this one...

**Comment by mpflanzer** [comment]
Thanks for the reporting this problem. My Xcode did not complain about incompatibilities with 10.9. Seems like one cannot trust this information. ;)
I will have a look at as soon as possible.

**Comment by mpflanzer** [comment]
I created a version without the requirement of storyboard support: https://github.com/mpflanzer/splitshow/releases/tag/0.9.6-alpha. The sources can be found under the new branch: https://github.com/mpflanzer/splitshow/tree/no_storyboard

It has the same features as the OS X 10.10 only version so you give it a try, @randi120. Please let me know if there are still problems. Otherwise please close the issue.

**Comment by randi120** [comment]
good news, the no_storyboard branch compiles on 10.9. 

However, it still doesn't run properly for me. See screenshot below. xcode reports it running and the app is running but there are no windows, and even the top bar is incomplete. 
I run into the same issue with the 0.9.6-alpha release. 
Any ideas what could be the problem? or how to troubleshoot?

![screenshot](https://cloud.githubusercontent.com/assets/5075878/7664681/64419104-fb60-11e4-886b-3696ec2ef4b8.png)

**Comment by mpflanzer** [comment]
@randi120 I missed to change the main view to the nib file instead of the storyboard. Xcode had the settings and files cached for me and did not make an update during rebuild such that I did not run into problems. Hopefully it will now work. I pushed the fixed code to the no_storyboard branch. If it runs without problems I will update the release, too. Could you please try again?

**Comment by randi120** [comment]
compiled and ran branch no_storyboard (7c2a5815603ec) without any problems on 10.9

thanks @mpflanzer! look forward to using it!
